#SITE CONFIGURATION

title: Daniel Enrique Cobbey
description: Musicologist
repository: "andrewstiefel/music-portfolio"
baseurl: 
url: "http://danielcobbey.com"

google_tag_manager: GTM-P7PZFVP

# SEO PLUGIN

social:
  name: Daniel Enrique Cobbey
  links:
    - https://www.facebook.com/cornonthecobbey
    - https://twitter.com/cornonthecobbey
    - https://www.instagram.com/cornonthecobbey
    - https://www.youtube.com/user/cornonthecobbey
    - https://github.com/danielcobbey
    
#THEME SETTINGS

navigation: # Navigation links
  - {name: 'Music', link: '/music'}
  - {name: 'Recordings', link: '/recordings'}
  - {name: 'Contact', link: '/contact'}
  
email: danielcobbey@gmail.com
twitter_username: cornonthecobbey
github_username: danielcobbey
instagram_username: cornonthecobbey
facebook_username: cornonthecobbey

#BUILD SETTINGS

markdown: kramdown
include: ['_pages']
permalink: /blog/:title

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

compress_html:
  clippings: all

plugins: 
  - jekyll-sitemap
  - jekyll-seo-tag
